### PR TITLE
PR for OML Fundamentals Workshop. WID: 7401

### PR DESCRIPTION
**Pull request by MoitreyeeHazarika**
Hi,

PR request for Oracle Machine Learning Fundamentals on Autonomous Database (WMS ID 7401). Contains new content on OML4R (lab 1) and text policy content in AutoML (lab 4)

Thanks
Moitreyee

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Workshop #7401's link in WMS is oml/oml-fun-on-adb, and it seems like you are updating files outside of this workshop. Please add the WMS IDs of all workshops that have been updated, or only keep the changes for #7401. Thanks!

**Comment by MoitreyeeHazarika** [comment]
Hi, 

Under oml folder, I work on 3 different workshops - oml-fun-on-adb, oml, and oml4py-adb. 
oml-workshops


I wanted to do a PR only for the workshop **oml-fun-on-adb (WMS: 7401)**. And for that, I clicked on oml-fun-on-adb in my fork, and clicked Pull Request. See attached screenshot. Let me know what I have missed here.  Thanks


oml-fun-on-adb

**Comment by madhusudhanrao-ppm** [comment]
Please check the folders & files in your PR, they seem to be 2 different workshops, one WMS ID 7401

image

**Comment by MoitreyeeHazarika** [comment]
Hi  Madhu, 

Yes, I am working on 2 different workshops under oml. 

- oml-fun-on-adb (WMS: 7401): Right now, I want these changes to be pushed to main.
- oml4py-adb (WMS 520):  This is work in progress. And I don't want these changes to be pushed to main.    

Hence, I created the PR from the oml-fun-on-adb  folder.

Thanks

**Review by madhusudhanrao-ppm — APPROVED** [review]

**Pull request merged**
