### PR TITLE
 Format WMSID 6941

### PR DESCRIPTION
**Pull request by oracleadrian**
# Add here your WMS ID

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

### CODE REVIEW

**Comment by shirschf** [comment]
Hello, the workshop URL is https://oracle-livelabs.github.io/pts/oml4sql/workshops/freetier/index.html but the pull request is in oracle-livelabs/oml (instead of pts). Is this the correct location?

**Review by shirschf — CHANGES_REQUESTED** [review]
Please see comment in conversation tab, is this the correct location?

**Comment by oracleadrian** [comment]
Checking the Livelabs repositories I see that my WMS ID 6941 workshop exists in two repositories.
oml
pts
I don't know what to do in this case.

**Comment by oracleadrian** [comment]
> Hello, the workshop URL is https://oracle-livelabs.github.io/pts/oml4sql/workshops/freetier/index.html but the pull request is in oracle-livelabs/oml (instead of pts). Is this the correct location?

Checking the Livelabs repositories I see that my WMS ID 6941 workshop exists in two repositories.
oml
pts
I don't know what to do in this case.

**Review by anooshapilli — APPROVED** [review]

**Comment by anooshapilli** [comment]
@oracleadrian Please sync your branch to merge the PR.

**Comment by oracleadrian** [comment]
Ready, branch updated

**Review by ahaikl — APPROVED** [review]

**Comment by ahaikl** [comment]
> Please see comment in conversation tab, is this the correct location?

@anooshapilli worked with Adrian to address this issue

**Review by shirschf — APPROVED** [review]

**Pull request merged**
